version: '2.0'

services:
  api:
    container_name: api
    restart: always
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db

  db:
    container_name: postgresdb
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  client:
    extends:
      file: ../frontend/docker-compose.yml
      service: client

volumes: 
 data: {}