version: '3.8'
services:
  client:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - .:/usr/share/nginx/html
  
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgresdb
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  web:
    extends:
      file: ../frontend/docker-compose.yml
      service: client

volumes: 
 data: {}