version: '3.8'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: "npm run dev"

  db:
    container_name: postgresdb
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  client:
    extends:
      file: ../frontend/docker-compose.yml
      service: client

volumes: 
 data: {}